version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: 'redis:latest'

  server:
    build:
      dockerfile: Dockerfile.dev
      # spell out the directory that has the Dockerfile
      context: ./server
    volumes:
      # don't override the node_modules folder
      - /app/node_modules
      # look in the local server folder for anything
      # else that should be in /app
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

