name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test

      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client-no-k8s ./client
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx-no-k8s  ./nginx
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-server-no-k8s ./server
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker-no-k8s ./worker

      #- run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-client-no-k8s
      #- run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx-no-k8s
      #- run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-server-no-k8s
      #- run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker-no-k8s

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to ElasticBeanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-gh
          environment_name: Multigh-env
          existing_bucket_name: ${{ secrets.AWS_S3_BUCKET_NAME }}
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

